local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Base Battles", "Ocean")
local Tab = Window:NewTab("Main")
local Section = Tab:NewSection("Main")
local AimlockScript = game:HttpGet("https://pastebin.com/raw/094LQMUG")
local Aimlock = loadstring(AimlockScript)()
Section:NewButton("Aimbot", "Enables a Aimlock in head", function()
    Aimlock.Enable()
    Aimlock.Start()
end)
